---
kind: Job
apiVersion: batch/v1
metadata:
  name: onboard-vcluster-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 3
  selector:
    matchLabels:
      job-name: onboard-vcluster-{{ .Release.Name }}
  template:
    metadata:
      name: vcluster-onboard-{{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      labels:
        job-name: onboard-vcluster-{{ .Release.Name }}
    spec:
        containers:
        - args:
            - /usr/local/openunison/onboard-cluster.sh
          image: {{ .Values.vcluster.job_image }}
          imagePullPolicy: Always
          name: vcluster-onboard
          resources: {}
          volumeMounts:
            - mountPath: /etc/openunison
              name: vcluster-helm-values
          env:
          - name: VCLUSTER_NAME
            value: {{ .Values.vcluster.name }}
          - name: VCLUSTER_NAMESPACE
            value: {{ .Values.vcluster.namespace }}
          - name: TREMOLO_HELM_REPO
            value: {{ .Values.vcluster.helm_repo_url }}
          - name: K8S_DASHBOARD_HELM_REPO
            value: {{ .Values.vcluster.kubernetes_dashboard_helm_repo_url }}
          - name: VCLUSTER_LABEL
            value: {{ .Values.vcluster.label }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - "all"
        dnsPolicy: ClusterFirst
        serviceAccount: vcluster-onboard-{{ .Release.Name }}
        serviceAccountName: vcluster-onboard-{{ .Release.Name }}
        restartPolicy: OnFailure
        securityContext:
          fsGroup: 433
          supplementalGroups: [433]
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 431
          runAsGroup: 433
        volumes:
        - name: vcluster-helm-values
          configMap:
            name: vcluster-helm-values-{{ .Release.Name }}
