---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openunison-operator-{{ .Release.Name }}-webhooks
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: openunison
  annotations:
    argocd.argoproj.io/sync-wave: "20"
subjects:
- kind: ServiceAccount
  name: openunison-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: openunison-operator-{{ .Release.Name }}-webhooks
  apiGroup: rbac.authorization.k8s.io