{{ if and (.Values.crd.deploy) (eq .Values.crd.betas true) }}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: users.openunison.tremolo.io
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: crd
    app.kubernetes.io/part-of: openunison
spec:
  group: openunison.tremolo.io
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Namespaced
  names:
    plural: users
    singular: user
    kind: User
    shortNames:
    - usr
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            sub:
              type: string
            groups:
              type: array
              items:
                type: string
            first_name:
              type: string
            last_name:
              type: string
            email:
              type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: oidc-sessions.openunison.tremolo.io
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: crd
    app.kubernetes.io/part-of: openunison
spec:
  group: openunison.tremolo.io
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Namespaced
  names:
    plural: oidc-sessions
    singular: oidc-session
    kind: OidcSession
    shortNames:
    - oidc
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            session_id:
              type: string
            client_id:
              type: string
            encrypted_id_token:
              type: string
            encrypted_access_token:
              type: string
            expires:
              type: string
            user_dn:
              type: string
            refresh_token:
              type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openunisons.openunison.tremolo.io
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: crd
    app.kubernetes.io/part-of: openunison
spec:
  group: openunison.tremolo.io
  versions:
    - name: v2
      served: true
      storage: true
  version: v2
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: openunisons
    singular: openunison
    kind: OpenUnison
    shortNames:
    - ou
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            image:
              type: string
            replicas:
              type: integer
            enable_activemq:
              type: boolean
            activemq_image:
              type: string
            dest_secret:
              type: string
            source_secret:
              type: string
            secret_data:
              type: array
              items:
                type: string
            openshift:
              type: object
              properties:
                git:
                  type: object
                  properties:
                    repo:
                      type: string
                    branch: 
                      type: string
                    dir:
                      type: string
                builder_image:
                  type: string
            hosts:
              type: array
              items:
                type: object
                properties:
                  names:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        env_var:
                          type: string
                  ingress_name: 
                    type: string
                  ingress_type:
                    type: string
                  secret_name:
                    type: string
                  annotations:
                    type: array
                    items:
                      type: object
                      properties:
                        name: 
                          type: string
                        value:
                          type: string
            deployment_data:
              type: object
              properties:
                tokenrequest_api:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    audience:
                      type: string
                    expirationSeconds:
                      type: integer
                readiness_probe_command:
                  type: array
                  items:
                    type: string
                liveness_probe_command:
                  type: array
                  items:
                    type: string
                node_selectors:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                pull_secret:
                  type: string
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        memory:
                          type: string
                        cpu:
                          type: string
                    limits:
                      type: object
                      properties:
                        memory:
                          type: string
                        cpu:
                          type: string

                
            non_secret_data:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  value:
                    type: string
            openunison_network_configuration:
              type: object
              properties:
                force_to_lower_case:
                  type: boolean
                open_port:
                  type: integer
                open_external_port:
                  type: integer
                secure_port:
                  type: integer
                secure_external_port:
                  type: integer
                force_to_secure:
                  type: boolean
                activemq_dir:
                  type: string
                client_auth:
                  type: string
                allowed_client_names:
                  type: array
                  items:
                    type: string
                ciphers:
                  type: array
                  items:
                    type: string
                path_to_deployment:
                  type: string
                path_to_env_file:
                  type: string
                secure_key_alias:
                  type: string
                allowed_tls_protocols:
                  type: array
                  items:
                    type: string
                quartz_dir:
                  type: string
                context_root:
                  type: string
                disable_http2:
                  type: boolean
                allow_un_escaped_chars:
                  type: string
                welecome_pages:
                  type: array
                  items:
                    type: string
                error_pages:
                  type: array
                  items:
                    type: object
                    properties:
                      code:
                        type: integer
                      location:
                        type: string
                redirect_to_context_root:
                  type: boolean
            saml_remote_idp:
              type: array
              items:
                type: object
                properties:
                  source:
                    type: object
                    properties:
                      url:
                        type: string
                      xml:
                        type: string
                  mapping:
                    type: object
                    properties:
                      entity_id:
                        type: string
                      post_url:
                        type: string
                      redirect_url:
                        type: string
                      logout_url:
                        type: string
                      signing_cert_alias:
                        type: string
                      encryption_cert_alias:
                        type: string
            run_sql:
              type: string
            key_store:
              type: object
              properties:
                update_controller:
                  type: object
                  properties:
                    image:
                      type: string
                    schedule:
                      type: string
                    days_to_expire:
                      type: integer
                static_keys:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      version:
                        type: integer
                trusted_certificates:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      pem_data:
                        type: string
                key_pairs:
                  type: object
                  properties:
                    create_keypair_template:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                    keys:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          tls_secret_name:
                            type: string
                          import_into_ks:
                            type: string
                            enum:
                            - keypair
                            - certificate
                            - none
                          replace_if_exists:
                            type: boolean
                          create_data:
                            type: object
                            properties:
                              target_namespace:
                                type: string
                              sign_by_k8s_ca:
                                type: boolean
                              server_name:
                                type: string
                              subject_alternative_names:
                                type: array
                                items:
                                  type: string
                              key_size:
                                type: integer
                              ca_cert:
                                type: boolean
                              delete_pods_labels:
                                type: array
                                items:
                                  type: string
                              patch_info:
                                type: object
                                properties:
                                  url:
                                    type: string
                                  annotation_name:
                                    type: string
                              secret_info:
                                type: object
                                properties:
                                  type_of_secret:
                                    type: string
                                  cert_name:
                                    type: string
                                  key_name:
                                    type: string
            status:
              type: object
              properties:
                conditions:
                  properties:
                    lastTransitionTime:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  type: object
                digest:
                  type: string
                idpCertificateFingerprints:
                  type: object
                  additionalProperties: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: trusts.openunison.tremolo.io
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: crd
    app.kubernetes.io/part-of: openunison
spec:
  group: openunison.tremolo.io
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Namespaced
  names:
    plural: trusts
    singular: trust
    kind: Trust
    shortNames:
    - trust
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            clientId:
              type: string
            clientSecret:
              type: object
              properties:
                secretName:
                  type: string
                keyName:
                  type: string
            publicEndpoint:
              type: boolean
            redirectURI:
              type: array
              items:
                type: string
            codeLastMileKeyName:
              type: string
            authChainName:
              type: string
            codeTokenSkewMilis:
              type: integer
            accessTokenTimeToLive:
              type: integer
            accessTokenSkewMillis:
              type: integer
            signedUserInfo:
              type: boolean
            verifyRedirect:
              type: boolean
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: portalurls.openunison.tremolo.io
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: crd
    app.kubernetes.io/part-of: openunison
spec:
  group: openunison.tremolo.io
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Namespaced
  names:
    plural: portalurls
    singular: portalurl
    kind: PortalUrl
    shortNames:
    - portalurl
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            label:
              type: string
            url:
              type: string
            org:
              type: string
            icon:
              type: string
            azRules:
              type: array
              items:
                type: object
                properties:
                  scope:
                    type: string
                  constraint:
                    type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: orgs.openunison.tremolo.io
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: crd
    app.kubernetes.io/part-of: openunison
spec:
  group: openunison.tremolo.io
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Namespaced
  names:
    plural: orgs
    singular: org
    kind: Org
    shortNames:
    - orgs
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            description:
              type: string
            uuid:
              type: string
            parent:
              type: string
            showInPortal:
              type: boolean
            showInRequestAccess:
              type: boolean
            showInReports:
              type: boolean
            azRules:
              type: array
              items:
                type: object
                properties:
                  scope:
                    type: string
                  constraint:
                    type: string
---
{{ end }}