{{ if .Values.openunison.naas.groups.internal.enabled }}
{{- $root := . -}}
{{ range $role := .Values.openunison.naas.groups.default }}
---
apiVersion: openunison.tremolo.io/v1
kind: Workflow
metadata:
  name: control-plane-namespace-{{ $role.name }}
  namespace: {{ $root.Release.Namespace }}
spec:
  description: ClusterRole admin for the $name$ namespace
  inList: true
  label: {{ $role.workflow.displayLabel }}
  orgId: org-cluster-control-plane-{{ $role.name }}
  dynamicConfiguration:
    dynamic: true
    className: com.tremolosecurity.unison.openshiftv3.wf.OpenShiftWorkflows
    params:
    - name: target
      value: k8s
    - name: kind
      value: /api/v1/namespaces?labelSelector=tremolo.io/request-access%3Denabled
  tasks: |-
           - taskType: addAttribute
             name: cluster
             value: k8s
             remove: false
             addToRequest: true
           - taskType: callWorkflow
             name: k8s-namespace-{{ $role.name }}
{{ end }}
{{ range $role := .Values.openunison.naas.groups.roles }}
---
apiVersion: openunison.tremolo.io/v1
kind: Workflow
metadata:
  name: control-plane-namespace-{{ $role.name }}
  namespace: {{ $root.Release.Namespace }}
spec:
  description: ClusterRole admin for the $name$ namespace
  inList: true
  label: {{ $role.workflow.displayLabel }}
  orgId: org-cluster-control-plane-{{ $role.name }}
  dynamicConfiguration:
    dynamic: true
    className: com.tremolosecurity.unison.openshiftv3.wf.OpenShiftWorkflows
    params:
    - name: target
      value: k8s
    - name: kind
      value: /api/v1/namespaces?labelSelector=tremolo.io/request-access%3Denabled
  tasks: |-
           - taskType: addAttribute
             name: cluster
             value: k8s
             remove: false
             addToRequest: true
           - taskType: callWorkflow
             name: k8s-namespace-{{ $role.name }}
{{ end }}

---
apiVersion: openunison.tremolo.io/v1
kind: Workflow
metadata:
  name: controlplane-approvers
  namespace: {{ .Release.Namespace }}
spec:
  description: Add new approvers
  inList: true
  label: $namespaceName$ Approver
  orgId: org-cluster-control-plane-approvers
  dynamicConfiguration:
    dynamic: true
    className: com.tremolosecurity.scalejs.ListClusterApproverGroups
    params:
    - name: cluster
      value: k8s
    - name: groupsAttribute
      value: groups
    - name: groupsAreDN
      value: "false"
    - name: groupPrefix
      value: approvers-k8s-
  tasks: |-
           - taskType: callWorkflow
             name: k8s-add-approver
{{ end }}
