---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationChain
metadata:
  name: enterprise-idp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: openunison-authchains
    app.kubernetes.io/part-of: openunison
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  level: 20
  root: o=Data
  authMechs:
{{ if .Values.active_directory }}
  - name: login-form
    required: required
    params:
      FORMLOGIN_JSP: "/auth/forms/defaultForm.jsp"
    secretParams: []
  - name: map
    required: required
    params:
      map: 
      - "uid|composite|${uid}"
      - "mail|composite|${mail}"
      - "givenName|composite|${givenName}"
      - "sn|composite|${sn}"
      - "displayName|composite|${displayName}"
      - "memberOf|user|memberOf"
{{ end }}
{{ if .Values.oidc }}
  - name: oidc
    required: required
    params:
      bearerTokenName: oidcBearerToken
      {{ if not .Values.oidc.client_id_is_secret  }}
      clientid: {{ .Values.oidc.client_id | quote }}
      {{ end }}
      {{ if .Values.oidc.issuer }}
      issuer: {{ .Values.oidc.issuer | quote }}
      {{ else }}
      idpURL: {{ .Values.oidc.auth_url | default "" | quote }}
      loadTokenURL: {{ .Values.oidc.token_url | default "" | quote }}
      restURL: {{ .Values.oidc.userinfo_url | default "" | quote }}
      {{ end }}
      responseType: code
      
      
      scope: {{ .Values.oidc.scopes | quote }}
      linkToDirectory: "false"
      noMatchOU: "oidc"
      lookupFilter: "(uid=${sub})"
      defaultObjectClass: inetOrgPerson
      uidAttr: sub
      hd: {{ .Values.oidc.domain | quote }}
      {{ if .Values.oidc.user_in_idtoken }}
      userLookupClassName: "com.tremolosecurity.unison.proxy.auth.openidconnect.loadUser.LoadJWTFromAccessToken"
      jwtTokenAttributeName: "id_token"
      {{ else }}
      userLookupClassName: "com.tremolosecurity.unison.proxy.auth.openidconnect.loadUser.LoadAttributesFromWS"
      {{ end }}
      {{ if hasKey .Values.oidc "forceauthentication" }}
      forceAuthentication : {{ .Values.oidc.forceauthentication | quote }}
      {{ else }}
      forceAuthentication : "true"
      {{ end }}
    secretParams:
    - name: secretid
      secretName: orchestra-secrets-source#[openunison.static-secret.suffix]
      secretKey: OIDC_CLIENT_SECRET
    {{ if .Values.oidc.client_id_is_secret }}
    - name: clientid
      secretName: orchestra-secrets-source#[openunison.static-secret.suffix]
      secretKey: OIDC_CLIENT_ID
    {{ end }}
  - name: map
    required: required
    params:
      map: 
      - "uid|composite|{{ print "${" .Values.oidc.claims.sub "}" }}"
      - "mail|composite|{{ print "${" .Values.oidc.claims.email "}" }}"
      - "givenName|composite|{{ print "${"  .Values.oidc.claims.given_name "}" }}"
      - "sn|composite|{{ print "${"  .Values.oidc.claims.family_name "}" }}"
      - "displayName|composite|{{ print "${"  .Values.oidc.claims.display_name "}" }}"
      - "memberOf|user|{{ .Values.oidc.claims.groups }}"
{{ end }}
{{ if .Values.github }}
  - name: github
    required: required
    params:
      bearerTokenName: githubToken
      clientid: {{ .Values.github.client_id }}
      scope: "user:read user:email read:org"
      linkToDirectory: "false"
      noMatchOU: github
      lookupFilter: "(uid=${login})"
      uidAttr: login
      defaultObjectClass: inetOrgPerson
    secretParams:
    - name: secretid
      secretName: orchestra-secrets-source#[openunison.static-secret.suffix]
      secretKey: GITHUB_SECRET_ID
  - name: az
    required: required
    params:
      rules: custom;github!{{ .Values.github.teams }}
  - name: map
    required: required
    params:
      map: 
      - "uid|user|login"
      - "mail|composite|${mail}"
      - "givenName|static|na"
      - "sn|static|na"
      - "displayName|composite|${name}"
      - "memberOf|user|groups"
{{ end }}
{{ if .Values.saml }}
  - name: saml2
    required: required
    params:
      {{ if .Values.saml.idp_url }}
      metadataUrl: "{{ .Values.saml.idp_url }}"
      {{ else }}
      metadataUrl: "/etc/saml2/metadata.xml"
      {{ end }}
      idpSigKeyName: 
      - idp-saml2-sig
      - idp-saml2-sig-1
      ldapAttribute: uid
      dnOU: saml
      defaultOC: inetOrgPerson
      authCtxRef: "{{ .Values.saml.authnCtxClassRef }}"
      spSigKey: unison-saml2-rp-sig
      sigAlg: "RSA-SHA256"
      signAuthnReq: "true"
      assertionsSigned: "#[SAML2_ASSERTION_SIGNED:true]"
      responsesSigned: "#[SAML2_RESPONSE_SIGNED:false]"
      assertionEncrypted: "false"
      spEncKey: ""
      forceToSSL: "false"
      dontLinkToLDAP: "true"
      logoutURL: "https://#[K8S_DASHBOARD_HOST]/logout"
      {{ if .Values.saml.logoutRedirectUrl }}
      idpRedirLogoutURL: "{{ .Values.saml.logoutRedirectUrl }}"
      {{ end }}
    secretParams: []
  - name: map
    required: required
    params:
      map: 
      - "uid|composite|${uid}"
      - "mail|composite|${mail}"
      - "givenName|composite|${givenName}"
      - "sn|composite|${sn}"
      - "displayName|composite|${displayName}"
      - "memberOf|user|memberOf"
{{ end }}
{{ if .Values.openunison.include_auth_chain }}
  - name: include
    params:
      chainName: {{ .Values.openunison.include_auth_chain }}
    required: required
{{ end }}
  - name: jit
    required: required
    params: 
      nameAttr: uid
      workflowName: jitdb
{{ if .Values.openunison.post_jit_workflow }}
  - name: jit
    required: required
    params: 
      nameAttr: uid
      workflowName: "{{ .Values.openunison.post_jit_workflow }}"
{{ end }}
  - name: genoidctoken
    required: required
    params:
      idpName: k8sidp
      trustName: kubernetes
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationChain
metadata:
  name: login-service
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  level: 20
  root: o=Tremolo
  authMechs:
  - name: login-service
    required: required
    params:
      chains: "Login=/login/auth"
      serviceUrl: "/auth/forms/chooseLogin.jsp"
      cookieName: "tremoloLoginChoice"
      cookieDays: "30"
    secretParams: []
{{ if .Values.enable_impersonation }}
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationChain
metadata:
  name: oauth2jwt
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  level: 20
  root: o=Tremolo
  authMechs:
  - name: oauth2jwt
    required: required
    params:
      issuer: "https://#[OU_HOST]/auth/idp/k8sIdp"
      validationKey: unison-saml2-rp-sig
      linkToDirectory: "false"
      noMatchOU: oauth2
      uidAttr: sub
      lookupFilter: "(sub=${sub})"
      userLookupClassName: inetOrgPerson
      defaultObjectClass: inetOrgPerson
      realm: kubernetes
      scope: auth
      audience: kubernetes
    secretParams: []
{{ end }}
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationChain
metadata:
  name: oauth2k8s
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  level: 20
  root: o=Tremolo
  authMechs:
  - name: oauth2k8s
    required: required
    params:
      k8sTarget: k8s
      linkToDirectory: "false"
      noMatchOU: oauth2
      uidAttr: username
      lookupFilter: "(uid=${sub})"
      defaultObjectClass: inetOrgPerson
      realm: kubernetes
      scope: auth
    secretParams: []
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationChain
metadata:
  name: oauth2jwt-login
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  level: 20
  root: o=Tremolo
  authMechs:
  - name: oauth2jwt
    required: required
    params:
      issuer: "https://#[OU_HOST]/auth/idp/k8s-login-cli"
      validationKey: unison-saml2-rp-sig
      linkToDirectory: "true"
      noMatchOU: oauth2
      uidAttr: sub
      lookupFilter: "(sub=${sub})"
      userLookupClassName: inetOrgPerson
      defaultObjectClass: inetOrgPerson
      realm: kubernetes
      scope: auth
      audience: cli-local
    secretParams: []
  - name: genoidctoken
    required: required
    params:
      idpName: k8sidp
      trustName: kubernetes