{{- $root := . -}}
{{ range $app := $root.Values.openunison.apps }}
---
apiVersion: openunison.tremolo.io/v1
kind: Application
metadata:
  name: k8s-app-{{ $app.name }}-{{ $root.Release.Name }}
  namespace: {{ $root.Release.Namespace }}
spec:
  azTimeoutMillis: 3000
  isApp: true
  urls:
  - hosts:
    - "{{ (urlParse $app.badgeUrl).host }}"
    filterChain:
    - className: com.tremolosecurity.proxy.filters.HideCookie
    - className: com.tremolosecurity.proxy.filters.SetNoCacheHeaders
    {{ if $app.injectToken }}
    {{ if $root.Values.enable_impersonation }}
    - className: com.tremolosecurity.proxy.filters.K8sInjectImpersonation
      params:
        targetName: k8s
        userNameAttribute: sub
        useLdapGroups: "false"
        groupAttribute: groups
    {{ end }}
    {{ end }}
    uri: "/"
    proxyTo: {{ $app.proxyTo }}
    authChain: k8s-app-{{ $app.name }}-{{ $root.Release.Name }}
    azRules:
    {{ $length := len $app.az_groups }}
    {{ if eq $length 0 }}
    - scope: dn
      constraint: o=Tremolo
    {{ else }}
    {{ range $az_group := $app.az_groups }}
    - scope: filter
      constraint: (groups={{ $az_group }})
    {{ end }}
    {{ end }}
{{ if $app.injectToken }}
{{ if not $root.Values.enable_impersonation }}
    results:
      azSuccess: oauth2bearer
{{ end }}
{{ else if $app.azSuccessResponse }}
    results:
      azSuccess: {{ $app.azSuccessResponse }}
{{ end }}
  cookieConfig:
    sessionCookieName: tremolosession
    domain: "{{ (urlParse $app.badgeUrl).host }}"
    secure: true
    httpOnly: true
    logoutURI: "/logout"
    timeout: {{ $root.Values.network.session_inactivity_timeout_seconds }}
    keyAlias: session-unison
{{ end }}