{{- $root := . -}}
{{ range $app := $root.Values.openunison.apps }}
---
apiVersion: openunison.tremolo.io/v1
kind: Trust
metadata:
  name: k8s-app-{{ $app.name }}-{{ $root.Release.Name }}
  namespace: {{ $root.Release.Namespace }}
spec:
  accessTokenSkewMillis: 120000
  accessTokenTimeToLive: 120000
  authChainName: login-service
  clientId: k8s-app-{{ $app.name }}-{{ $root.Release.Name }}
  codeLastMileKeyName: lastmile-oidc
  codeTokenSkewMilis: 60000
  publicEndpoint: false
  redirectURI:
  - https://{{ (urlParse $app.badgeUrl).host }}/auth/oidc
  signedUserInfo: true
  verifyRedirect: true
  clientSecret:
    keyName: K8S_DB_SECRET
    secretName: orchestra-secrets-source
{{ end }}