{{ if .Values.headlamp.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  annotations:
    argocd.argoproj.io/sync-wave: "25"
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.openunison.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: headlamp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: headlamp
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - -in-cluster
        - -plugins-dir=/headlamp/plugins
        - -base-url=/headlamp
        - -tls-cert-path=/etc/tls-keys/tls.crt
        - -tls-key-path=/etc/tls-keys/tls.key
        {{- with .Values.headlamp.config.enableHelm }}
        - "-enable-helm"
        {{- end }}
        {{- if .Values.headlamp.config.watchPlugins }}
        - "-watch-plugins-changes"
        {{- end }}
        
        image: {{ .Values.headlamp.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: tls-keys
          mountPath: "/etc/tls-keys"
          readOnly: true
        - name: homedir
          mountPath: /home/headlamp/.config
        - name: tmpdir
          mountPath: /tmp
        {{ if .Values.headlamp.pluginsManager.enabled }}
        - name: plugins-dir
          mountPath: /headlamp/plugins
        {{ end }}
        - name: openunison-headlamp-plugin
          mountPath: /headlamp/plugins/openunison-headlamp-plugin
        {{- with .Values.headlamp.volumeMounts}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /headlamp/
            port: http
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: headlamp
        ports:
        - containerPort: 4466
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /headlamp/
            port: http
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        {{ if .Values.headlamp.resources }}
        resources:
          {{- toYaml .Values.headlamp.resources | nindent 12 }}
        {{ end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          readOnlyRootFilesystem: true
          privileged: false
          {{ if .Capabilities.APIVersions.Has "project.openshift.io/v1/Project" }}
          runAsNonRoot: true
          {{ else }}
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 100
          runAsGroup: 101
          {{ end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      {{- if .Values.headlamp.pluginsManager.enabled }}
      - name: headlamp-plugin
        image: {{ .Values.headlamp.pluginsManager.baseImage }}
        command: ["/bin/sh", "-c"]
        {{- if .Values.headlamp.pluginsManager.env }}
        env:
          {{- toYaml .Values.headlamp.pluginsManager.env | nindent 10 }}
        {{- end }}
        args:
          - |
            if [ -f "/config/plugin.yml" ]; then
              echo "Installing plugins from config..."
              cat /config/plugin.yml
              # Use a writable cache directory
              export NPM_CONFIG_CACHE=/tmp/npm-cache
              # Use a writable config directory
              export NPM_CONFIG_USERCONFIG=/tmp/npm-userconfig
              mkdir -p /tmp/npm-cache /tmp/npm-userconfig
              npx --yes @headlamp-k8s/pluginctl@{{ .Values.headlamp.pluginsManager.version }} install --config /config/plugin.yml --folderName /headlamp/plugins --watch
            fi
        volumeMounts:
          - name: plugins-dir
            mountPath: /headlamp/plugins
          - name: plugin-config
            mountPath: /config
          - name: plugin-tmp
            mountPath: /tmp
          - name: openunison-headlamp-plugin
            mountPath: /headlamp/plugins/openunison-headlamp-plugin
          {{- with .Values.headlamp.pluginsManager.volumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{ if .Values.headlamp.pluginsManager.resources}}
        resources:
          {{- toYaml .Values.headlamp.pluginsManager.resources | nindent 10 }}
        {{ end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          readOnlyRootFilesystem: true
          privileged: false
          {{ if .Capabilities.APIVersions.Has "project.openshift.io/v1/Project" }}
          runAsNonRoot: true
          {{ else }}
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 100
          runAsGroup: 101
          {{ end }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccount: headlamp
      serviceAccountName: headlamp
      terminationGracePeriodSeconds: 30
      {{- if .Values.services.tolerations }}
      tolerations:
      {{- range .Values.services.tolerations }}
      - {{- if .key }}
        key: {{ .key }}
        {{- end }}
        {{- if .effect }}
        effect: {{ .effect }}
        {{- end }}
        {{- if .operator }}
        operator: {{ .operator }}
        {{- end }}
        {{- if .value }}
        value: {{ .value }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{ $length := len .Values.services.node_selectors }}
      {{ if eq $length 0  }}
      nodeSelector: {}
      {{ else }}
      nodeSelector: {{ range $key,$value := .Values.services.node_selectors }}
        {{ $key }}: {{ $value | quote }}
      {{ end }}
      {{ end }}
      {{ if .Values.services.pullSecret }}
      imagePullSecrets:
      - name: {{  .Values.services.pullSecret | quote }}
      {{ end }}
      {{ if .Values.services.affinity }}
      affinity:
        {{- toYaml .Values.services.affinity | nindent 8 }}
      {{ end }}
      {{ if .Values.network.enableHostNetwork }}
      hostNetwork: true
      {{ else }}
      hostNetwork: false
      {{ end }}
      volumes:
      - name: tls-keys
        secret:
            secretName: headlamp-tls
      - name: homedir
        emptyDir: {}
      - name: tmpdir
        emptyDir: {}
      # openunison headlamp plugin
      - name: openunison-headlamp-plugin
        configMap:
          name: openunison-headlamp-plugin
      {{ if .Values.headlamp.pluginsManager.enabled }}
      - name: plugin-tmp
        emptyDir: {}
      - name: plugins-dir
        emptyDir: {}
      - name: plugin-config
        configMap:
          name: headlamp-plugin-config
      {{- with .Values.headlamp.volumes}}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.headlamp.service_name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 4466
  selector:
    app.kubernetes.io/name: headlamp
{{ end }}