{{ if not .Values.openunison.enable_provisioning }}
---
apiVersion: openunison.tremolo.io/v1
kind: Org
metadata:
  name: local-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: openunison-orgs
    app.kubernetes.io/part-of: openunison
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  label: "#[K8S_DEPLOYMENT_NAME:Local Deployment]"
  azRules:
  {{ if .Values.openunison.enable_provisioning }}
  {{ if .Values.openunison.naas.groups.external.enabled }}
  - constraint: (groups=k8s-cluster-k8s-administrators{{ .Values.openunison.naas.groups.external.suffix }})
    scope: filter
  {{ end }}
  {{ if .Values.openunison.naas.groups.internal.enabled }}
  - constraint: (groups=k8s-cluster-k8s-administrators{{ .Values.openunison.naas.groups.internal.suffix }})
    scope: filter
  {{ end }}
  {{ range $role := .Values.openunison.naas.groups.default }}
  - constraint: (groups=k8s-namespace-{{ $role.name }}-k8s-*)
    scope: filter
  {{ end }}
  {{ range $role := .Values.openunison.naas.groups.roles }}
  - constraint: (groups=k8s-namespace-{{ $role.name }}-k8s-*)
    scope: filter
  {{ end }}
  {{ else }}
  {{ $length := len .Values.openunison.az_groups }}
  {{ if eq $length 0 }}
  - scope: dn
    constraint: o=Tremolo
  {{ else }}
  {{ range $az_group := .Values.openunison.az_groups }}
  - scope: filter
    constraint: (groups={{ $az_group }})
  {{ end }}
  {{ end }}
  {{ end }}
  description: "#[K8S_DEPLOYMENT_DESC:Current Cluster]"
  parent: B158BD40-0C1B-11E3-8FFD-0800200C9A66
  showInPortal: true
  showInReports: false
  showInRequestAccess: false
  uuid: b1bf4c92-7220-4ad2-91af-ee0fe0af7312
{{ end }}