network:
  openunison_host: "k8sou.apps.domain.int"
  dashboard_host: "k8sdb.apps.domain.int"
  api_server_host: "k8sapi.apps.domain.int"
  session_inactivity_timeout_seconds: 900
  k8s_url: https://k8s-installer-master.tremolo.lan:6443
  createIngressCertificate: true
  ingress_type: nginx
  ingress_annotations: {}
  

cert_template:
  ou: "Kubernetes"
  o: "MyOrg"
  l: "My Cluster"
  st: "State of Cluster"
  c: "MyCountry"

image: "ghcr.io/openunison/openunison-k8s:1.0.38"
amq_image: "ghcr.io/tremolosecurity/activemq-docker:5.0.16"
myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: kubernetes
enable_impersonation: true
myvd_configmap: myvd

dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard
  enabled: true
certs:
  use_k8s_cm: false

trusted_certs: []


#active_directory:
#  base: cn=users,dc=ent2k12,dc=domain,dc=com
#  host: "192.168.2.75"
#  port: "636"
#  bind_dn: "cn=Administrator,cn=users,dc=ent2k12,dc=domain,dc=com"
#  con_type: ldaps
#  srv_dns: "false"

database:
  hibernate_dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  quartz_dialect: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://dbs.tremolo.lan:3308/unison
  user: root
  validation: SELECT 1

smtp:
  host: smtp.gmail.com
  port: 587
  user: donotreply@domain.com
  from: donotreply@domain.com
  tls: true

monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s

impersonation:
  use_jetstack: true
  jetstack_oidc_proxy_image: ghcr.io/tremolosecurity/kube-oidc-proxy:1.0.6
  explicit_certificate_trust: true
  ca_secret_name: ou-tls-certificate

network_policies:
  enabled: true
  ingress:
    enabled: true
    labels:
      app.kubernetes.io/name: ingress-nginx
  monitoring:
    enabled: true
    labels:
      app.kubernetes.io/name: monitoring
  apiserver:
    enabled: true
    labels:
      app.kubernetes.io/name: kube-system

services:
  enable_tokenrequest: false
  token_request_audience: api
  token_request_expiration_seconds: 600
  node_selectors: []
  tolerations: []
  pullSecret: ""
  liveness_probe:
  - /usr/local/openunison/bin/check_alive.sh
  - "https://127.0.0.1:8443/auth/idp/k8sIdp/.well-known/openid-configuration"
  - "issuer"
  - "https://127.0.0.1:8443/check_alive"
  - "alive"
  readiness_probe:
  - /usr/local/openunison/bin/check_alive.sh
  - "https://127.0.0.1:8443/auth/idp/k8sIdp/.well-known/openid-configuration"
  - "issuer"
  - "https://127.0.0.1:8443/check_alive"
  - "alive"

openunison:
  imagePullPolicy: Always
  authentication:
    refresh_token:
      grace_period_millis: 0
  replicas: 1
  non_secret_data: {}
  secrets: []
  role_attribute: groups
  groups:
    areJson: "false"
  html:
    image: ghcr.io/openunison/openunison-k8s-html:1.0.0
    legacy: true
    theme:
      startPage: front-page
      colors:
        primary: 
          main: "#AC1622"
          dark: "#780f17"
          light: "#bc444e"
        secondary:
          main: "#16aca0"
          dark: "#0f7870"
          light: "#44bcb3"
        error: "#ff1744"
        

  enable_provisioning: false
  enable_activemq: true
  az_groups: []
  precheck:
    image: ghcr.io/tremolosecurity/python3:1.0.0
  use_standard_jit_workflow: true
  management_proxy:
    enabled: false
  naas:
    ops:
      searchBases: {}
      approveChecked: false
      showPreApprove: true
      approvedLabel: Approved
      deniedLabel: Denied
      reasonApprovedLabel: Reason for approval
      reasonDeniedLabel: Reason for denial
    forms:
      new_namespace:
        use_default: true
    workflows:
      new_namespace:
        use_default: true
    
    groups:
      default:
      - name: administrators
        bindings:
          - type: ClusterRole
            binding: admins
            name: admin
        description: Manage kubernetes namespace $cluster$ $nameSpace$
        workflow:
          label: "namespace administrator"
          displayLabel: $name$ Administrator
          emailTemplate: Approve administrator access to $cluster$ $name$
          approvalLabel: Approve administrator access for $cluster$ - $name$
          userNotification:
            subject: Admin access to $cluster$ $name$ approved
            message: Your access has been approved
          org:
            label: Administrators
            description: Namespace Administrators
        external:
          fieldName: adminGroup
          label: "Administrator Group"
          errorMessage: "Invalid administrator group"
      - name: viewer
        description: View kubernetes namespace $cluster$ $nameSpace$
        bindings:
          - type: ClusterRole
            binding: viewers
            name: view
        external:
          fieldName: viewerGroup
          label: "Viewer Group"
          errorMessage: "Invalid viewer group"
        workflow:
          label: "namespace viewer"
          displayLabel: $name$ Administrator
          emailTemplate: Approve viewer access to $cluster$ $name$
          approvalLabel: Approve viewer access for $cluster$ - $name$
          userNotification:
            subject: View access to $cluster$ $name$ approved
            message: Your access has been approved
          org:
            label: Viewers
            description: Namespace Viewers
      internal:
        enabled: true
        suffix: "-internal"
      external:
        suffix: "-external"
        enabled: false
        admin_group: "CN=openunison-admins,CN=Users,DC=ent2k12,DC=domain,DC=com"
        cluster_admin_group: "CN=k8s_login_ckuster_admins,CN=Users,DC=ent2k12,DC=domain,DC=com"
    reasons: []