{{ if eq .Values.network.ingress_type "istio" }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: openunison-gateway-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: ingress-istio
    app.kubernetes.io/part-of: openunison
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  selector:
    {{ range $key,$value := .Values.network.istio.selectors }}
        {{ $key }}: {{ quote $value }}
    {{ end }}
  servers:
  - hosts:
    - {{ .Values.network.openunison_host }}
    {{ if .Values.dashboard.enabled }}
    - {{ .Values.network.dashboard_host }}
    {{ end }}
    {{ if and (eq .Values.enable_impersonation true) (eq .Values.impersonation.use_jetstack false ) }}
    - {{ .Values.network.api_server_host }}
    {{ end }}
    {{- $root := . -}}
    {{ range $app := $root.Values.openunison.apps }}
    - {{ (urlParse $app.badgeUrl).host }}
    {{ end }}
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - {{ .Values.network.openunison_host }}
    {{ if .Values.dashboard.enabled }}
    - {{ .Values.network.dashboard_host }}
    {{ end }}
    {{ if and (eq .Values.enable_impersonation true) (eq .Values.impersonation.use_jetstack false ) }}
    - {{ .Values.network.api_server_host }}
    {{ end }}
    {{ range $app := $root.Values.openunison.apps }}
    - {{ (urlParse $app.badgeUrl).host }}
    {{ end }}
    port:
      name: https-443
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ .Values.network.ingress_certificate }}
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: openunison-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: ingress-istio
    app.kubernetes.io/part-of: openunison
spec:
  gateways:
  - openunison-gateway-{{ .Release.Name }}
  hosts:
  - {{ .Values.network.openunison_host }}
  {{ if .Values.dashboard.enabled }}
  - {{ .Values.network.dashboard_host }}
  {{ end }}
  {{ if and (eq .Values.enable_impersonation true) (eq .Values.impersonation.use_jetstack false ) }}
  - {{ .Values.network.api_server_host }}
  {{ end }}
  {{ range $app := $root.Values.openunison.apps }}
  - {{ (urlParse $app.badgeUrl).host }}
  {{ end }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: openunison-{{ .Release.Name }}
        port:
          number: 80
{{ if and (eq .Values.enable_impersonation true) (eq .Values.impersonation.use_jetstack true ) }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: openunison-api-gateway-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: ingress-istio
    app.kubernetes.io/part-of: openunison
spec:
  selector:
    {{ range $key,$value := .Values.network.istio.selectors }}
        {{ $key }}: {{ quote $value }}
    {{ end }}
  servers:
  - hosts:
    - {{ .Values.network.api_server_host }}
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - {{ .Values.network.api_server_host }}
    port:
      name: https-443
      number: 443
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: openunison-api-{{ .Release.Name }}-jetstack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: ingress-istio
    app.kubernetes.io/part-of: openunison
spec:
  gateways:
  - openunison-api-gateway-{{ .Release.Name }}
  hosts:
  - {{ .Values.network.api_server_host }}
  tls:
  - match:
    - port: 443
      sniHosts:
      - {{ .Values.network.api_server_host }}
    route:
    - destination:
        host: kube-oidc-proxy-{{ .Release.Name }}
        port:
          number: 443
{{ end }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: openunison-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: ingress-istio
    app.kubernetes.io/part-of: openunison
spec:
  host: openunison-{{ .Release.Name }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: openunison-{{ .Release.Name }}
          path: /
          ttl: 0s
    tls:
      mode: ISTIO_MUTUAL
{{ end }}