{{ if and (eq .Values.enable_impersonation true) (eq .Values.impersonation.use_jetstack true)  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-oidc-proxy-{{ .Release.Name }}
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: kube-oidc-proxy
    app.kubernetes.io/part-of: openunison
  name: kube-oidc-proxy-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{ if eq .Values.network.ingress_type "traefik" }}
  {{ if .Values.network.traefik.secure }} 
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    traefik.ingress.kubernetes.io/service.serversscheme: https
  {{ else }}
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  {{ end }}
  {{ else }}
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  {{ end }}
spec:
  replicas: {{ .Values.openunison.replicas }}
  selector:
    matchLabels:
      app: kube-oidc-proxy-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: kube-oidc-proxy-{{ .Release.Name }}
        app.kubernetes.io/name: openunison
        app.kubernetes.io/instance: openunison-{{ .Release.Name }}
        app.kubernetes.io/component: kube-oidc-proxy
        app.kubernetes.io/part-of: openunison
    spec:
      serviceAccountName: openunison-{{ .Release.Name }}
      containers:
      - image: {{ .Values.impersonation.jetstack_oidc_proxy_image}}
        ports:
        - containerPort: 8443
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        name: kube-oidc-proxy-{{ .Release.Name }}
        command: ["kube-oidc-proxy"]
        args:
          - "--secure-port=8443"
          - "--tls-cert-file=/etc/oidc/tls/crt.pem"
          - "--tls-private-key-file=/etc/oidc/tls/key.pem"
          - "--oidc-client-id=kubernetes"
          - "--oidc-issuer-url=https://{{ .Values.network.openunison_host }}/auth/idp/k8sIdp"
          - "--oidc-username-claim=sub"
          - "--oidc-groups-claim=groups"
          {{ if .Values.impersonation.explicit_certificate_trust }}
          - "--oidc-ca-file=/etc/oidc/oidc-ca.pem"
          {{ else }}
          - "--oidc-ca-file=/etc/ssl/certs/ca-certificates.crt"
          {{ end }}
        imagePullPolicy: {{ .Values.openunison.imagePullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "all"
        volumeMounts:
          {{ if .Values.impersonation.explicit_certificate_trust }}
          - name: kube-oidc-proxy-config
            mountPath: /etc/oidc
            readOnly: true
          {{ end }}
          - name: kube-oidc-proxy-tls
            mountPath: /etc/oidc/tls
            readOnly: true
          {{ if .Values.services.enable_tokenrequest | default false }}
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: ou-token
          {{ end }}
        {{ if .Values.impersonation.resources }}
        resources:
          {{ if .Values.impersonation.resources.requests }}
          requests:
            {{ if .Values.impersonation.resources.requests.memory }}
            memory: {{ quote .Values.impersonation.resources.requests.memory }}
            {{ end }}
            {{ if .Values.impersonation.resources.requests.cpu }}
            cpu: {{ quote .Values.impersonation.resources.requests.cpu }}
            {{ end }}
          {{ end }}
          {{ if .Values.impersonation.resources.limits }}
          limits:
            {{ if .Values.impersonation.resources.limits.memory }}
            memory: {{ quote .Values.impersonation.resources.limits.memory }}
            {{ end }}
            {{ if .Values.impersonation.resources.limits.cpu }}
            cpu: {{ quote .Values.impersonation.resources.limits.cpu }}
            {{ end }}
          {{ end }}
        {{ end }}
      volumes:
        {{ if .Values.impersonation.explicit_certificate_trust }}
        - name: kube-oidc-proxy-config
          secret:
            secretName: {{ .Values.impersonation.ca_secret_name }}
            items:
            - key: tls.crt
              path: oidc-ca.pem
        {{ end }}
        {{ if .Values.services.enable_tokenrequest | default false }}
        - name: ou-token
          projected:
            defaultMode: 420
            sources:
            - serviceAccountToken:
                audience: {{ .Values.services.token_request_audience | default "https://kubernetes.default.svc.cluster.local" }}
                expirationSeconds: {{ .Values.services.token_request_expiration_seconds | default 60000 }}
                path: "token"
            - configMap:
                items:
                - key: "ca.crt"
                  path: "ca.crt"
                name: "kube-root-ca.crt"
            - configMap:
                items:
                - key: namespace
                  path: namespace
                name: namespace-holder
        {{ end }}
        - name: kube-oidc-proxy-tls
          secret:
            secretName: unison-tls
            items:
            - key: tls.crt
              path: crt.pem
            - key: tls.key
              path: key.pem
      {{ $length := len .Values.services.node_selectors }}
      {{ if eq $length 0  }}
      nodeSelector: {}
      {{ else }}
      nodeSelector: {{ range $key,$value := .Values.services.node_selectors }}
        {{ $key }}: {{ quote $value }}
      {{ end }}
      {{ end }}

      {{ if .Values.services.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.services.pullSecret }}
      {{ end }}
      automountServiceAccountToken: {{ not (.Values.services.enable_tokenrequest | default false) }}
      {{ if .Capabilities.APIVersions.Has "project.openshift.io/v1/Project" }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      {{ else }}
      securityContext:
        fsGroup: 10001
        supplementalGroups: [10001]
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
      {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kube-oidc-proxy-{{ .Release.Name }}
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: kube-oidc-proxy
    app.kubernetes.io/part-of: openunison
  name: kube-oidc-proxy-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{ if eq .Values.network.ingress_type "traefik" }}
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    {{ if .Values.network.traefik.secure }} 
    traefik.ingress.kubernetes.io/service.serversscheme: https
    {{ end }}
  {{ end }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
    name: https-kube-oidc-proxy
  selector:
    app: kube-oidc-proxy-{{ .Release.Name }}
  type: "{{ .Values.network.service_type | default "ClusterIP" }}"
{{ end }}
