{{ if .Values.openunison.naas.groups.internal.enabled }}
{{- $root := . -}}
{{ range $role := .Values.openunison.naas.groups.default }}
---
apiVersion: openunison.tremolo.io/v1
kind: Org
metadata:
  name: control-plane-namespace-{{ $role.name}}
  namespace: {{ $root.Release.Namespace }}
spec:
  label: {{ $role.workflow.org.label }}
  azRules:
  - constraint: o=Tremolo
    scope: dn
  description: {{ $role.workflow.org.description }}
  parent: org-cluster-control-plane
  showInPortal: false
  showInReports: false
  showInRequestAccess: true
  uuid: org-cluster-control-plane-{{ $role.name}}
{{ end }}
{{ range $role := .Values.openunison.naas.groups.roles }}
---
apiVersion: openunison.tremolo.io/v1
kind: Org
metadata:
  name: control-plane-namespace-{{ $role.name}}
  namespace: {{ $root.Release.Namespace }}
spec:
  label: {{ $role.workflow.org.label }}
  azRules:
  - constraint: o=Tremolo
    scope: dn
  description: {{ $role.workflow.org.description }}
  parent: org-cluster-control-plane
  showInPortal: false
  showInReports: false
  showInRequestAccess: true
  uuid: org-cluster-control-plane-{{ $role.name}}
{{ end }}
---
apiVersion: openunison.tremolo.io/v1
kind: Org
metadata:
  name: control-plane-approvers
  namespace: {{ .Release.Namespace }}
spec:
  label: Approvers
  azRules:
  - constraint: o=Tremolo
    scope: dn
  description: Approvers
  parent: org-cluster-control-plane
  showInPortal: false
  showInReports: false
  showInRequestAccess: true
  uuid: org-cluster-control-plane-approvers
{{ end }}