---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openunison-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: openunison-{{ .Values.argowf.openunison_release_name }}  # The name of the ServiceAccount being granted access
    namespace: {{ .Release.Namespace }}  # The namespace where the ServiceAccount exists