{{ if not .Values.operator.legacy }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openunison-operator
    app.kubernetes.io/name: openunison-operator
    app.kubernetes.io/instance: openunison-operator-{{ .Release.Name }}
    app.kubernetes.io/version: "{{ .Release.Version }}"
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: openunison
  name: openunison-operator
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openunison-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openunison-operator
        app.kubernetes.io/name: openunison-operator
        app.kubernetes.io/instance: openunison-operator-{{ .Release.Name }}
        app.kubernetes.io/version: "{{ .Release.Version }}"
        app.kubernetes.io/component: operator
        app.kubernetes.io/part-of: openunison
    spec:
      containers:
      - env:
        - name: CA_CERTS_PATH
          value: /usr/lib/jvm/java-17-openjdk-amd64/lib/security/cacerts
        - name: JAVA_OPTS
          value: -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom -Dsun.net.inetaddr.ttl=0 -Djava.security.krb5.conf=/etc/krb5-local/krb5.conf -Djava.security.krb5.debug=true
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{ if .Values.kerberos  }}
        {{ if .Values.kerberos.enabled }}
        - name: KRB5_CONFIG
          value: /etc/krb5-local/krb5.conf
        - name: KRB5RCACHEDIR
          value: /dev/shm
        - name: KRB5CCNAME
          value: /dev/shm/ccache
        {{ end }}
        {{ end }}
        image: {{ .Values.operator.image }}
        command:
        - java
        {{ if .Values.kerberos }}
        {{ if .Values.kerberos.enabled }}
        - -Djava.security.krb5.conf=/etc/krb5-local/krb5.conf
        - -Djava.security.krb5.debug=true
        - -Djava.security.auth.login.config=/etc/krb5-local/SQLJDBCDriver.conf
        {{ end }}
        {{ end }}
        - -jar
        - /usr/local/ouoperator/ouoperator.jar
        - operator
        - https://kubernetes.default.svc
        - {{ .Release.Namespace }}
        - /var/run/secrets/kubernetes.io/serviceaccount/token
        - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - "2,3,4,5,6"
        - "{{ join "," .Values.operator.validators }}/{{ join "," .Values.operator.mutators }}"
        imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
        name: openunison-operator
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          {{ if .Capabilities.APIVersions.Has "project.openshift.io/v1/Project" }}
          runAsNonRoot: true
          {{ else }}
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 431
          runAsGroup: 433
          {{ end }}
        volumeMounts:
        - mountPath: /etc/extraMaps
          name: extra-maps
          readOnly: true
        {{ if and .Values.kerberos  }}
        {{ if .Values.kerberos.enabled}}
        - mountPath: /etc/krb5-local
          name: krb
          readOnly: true
        {{ end }}
        {{ end }}
        {{ if .Values.operator.resources }}
        resources:
          {{ if .Values.operator.resources.requests }}
          requests: 
            {{ if .Values.operator.resources.requests.memory }}
            memory: {{ .Values.operator.resources.requests.memory | quote }}
            {{ end }}
            
            {{ if .Values.operator.resources.requests.cpu }}
            cpu: {{ .Values.operator.resources.requests.cpu | quote }}
            {{ end }}
          
          {{ end }}

          {{ if .Values.operator.resources.limits }}
          limits: 
            {{ if .Values.operator.resources.limits.memory }}
            memory: {{ .Values.operator.resources.limits.memory | quote }}
            {{ end }}
            
            {{ if .Values.operator.resources.limits.cpu }}
            cpu: {{ .Values.operator.resources.limits.cpu | quote }}
            {{ end }}
          
          {{ end }}
        {{ end }}
      {{ if .Values.kerberos }}
      {{ if .Values.kerberos.enabled }}
      - image: {{ .Values.kerberos.sidecar_image }}
        name: krb-sidecar
        {{ if not .Values.kerberos.keytab }}
        command:
          - /reinit-pwd.sh
        {{ end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          {{ if .Capabilities.APIVersions.Has "project.openshift.io/v1/Project" }}
          runAsNonRoot: true
          {{ else }}
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 431
          runAsGroup: 433
          {{ end }}
        env:
        - name: KRB5CCNAME
          value: /dev/shm/ccache
        - name: KRB5_CONFIG
          value: /etc/krb5-local/krb5.conf
        - name: REKINIT_PERIOD
          value: "3600"
        - name: SECRETS
          value: /etc/krb5-keytabs
        {{ if .Values.kerberos.keytab }}
        - name: KEYTAB
          value: {{ .Values.kerberos.keytab }}
        {{ end }}
        - name: PRINCIPAL
          value: {{ .Values.kerberos.principal }}
        - name: KRB5RCACHEDIR
          value: /dev/shm
        volumeMounts:
          - mountPath: /etc/krb5-local
            name: krb
            readOnly: true
          - mountPath: /etc/krb5-keytabs
            name: krb-keytab
            readOnly: true
      {{ end }}  
      {{ end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccount: openunison-operator
      {{ if .Capabilities.APIVersions.Has "project.openshift.io/v1/Project" }}
      securityContext:
        runAsNonRoot: true
      {{ else }}
      securityContext:
        fsGroup: 433
        supplementalGroups: [433]
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 431
        runAsGroup: 433
      {{ end }}
      volumes:
        - name: extra-maps
          emptyDir: {}
        {{ if .Values.kerberos }}
        {{ if .Values.kerberos.enabled}}
        - name: krb
          configMap:
            name: kerb-config
        - name: krb-keytab
          secret:
            secretName: kerb-keytab{{ .Values.openunison.secret_ext }}
        {{ end }}
        {{ end }}
      {{ $length := len .Values.services.node_selectors }}
      {{ if eq $length 0  }}
      nodeSelector: {}
      {{ else }}
      nodeSelector: {{ range $key,$value := .Values.services.node_selectors }}
        {{ $key }}: {{ $value | quote }}
      {{ end }}
      {{ end }}
      {{- if .Values.services.tolerations }}
      tolerations:
      {{- range .Values.services.tolerations }}
      - {{- if .key }}
        key: {{ .key }}
        {{- end }}
        {{- if .effect }}
        effect: {{ .effect }}
        {{- end }}
        {{- if .operator }}
        operator: {{ .operator }}
        {{- end }}
        {{- if .value }}
        value: {{ .value }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{ if .Values.services.pullSecret }}
      imagePullSecrets:
      - name: {{  .Values.services.pullSecret | quote }}
      {{ end }}
{{ end }}