{{ if .Values.openunison.naas.groups.privilegedAccessGroup }}
---
apiVersion: openunison.tremolo.io/v1
kind: Workflow
metadata:
  name: disable-break-glass-cluster
  namespace: {{ .Release.Namespace }}
spec:
  description: Disable cluster break-glass access
  inList: false
  label: Disable break glass
  orgId: 663b4074-eb34-4028-ac09-19de8886f816 
  tasks: |-
      - taskType: customTask
        className: com.tremolosecurity.provisioning.tasks.DeleteK8sObject
        params:
          targetName: $cluster$
          kind:  ClusterRoleBinding
          url: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/break-glass
{{ end }}