{{ if not .Values.openunison.enable_provisioning }}
{{ if .Values.openunison.use_standard_jit_workflow }}
---
apiVersion: openunison.tremolo.io/v1
kind: Workflow
metadata:
  name: jitdb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: openunison-workflows
    app.kubernetes.io/part-of: openunison
    tremolo.io/wf-type: login
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  description: JIT
  inList: false
  label: JIT
  orgId: 687da09f-8ec1-48ac-b035-f2f182b9bd1e
  dynamicConfiguration:
    dynamic: false
    className: ""
    params: []
  tasks: |-
           {{ if .Values.github }}
           - taskType: customTask
             className: com.tremolosecurity.unison.proxy.auth.github.MergeGithubGroups
             params: {}
           {{ else }}
           - taskType: customTask
             className: com.tremolosecurity.provisioning.customTasks.Attribute2Groups
             params:
               attributeName: memberOf
           {{ end }}
           - taskType: mapping
             strict: true
             map:
             - targetAttributeName: TREMOLO_USER_ID
               sourceType: user
               targetAttributeSource: uid
             - targetAttributeName: sub
               sourceType: user
               targetAttributeSource: uid
             - targetAttributeName: email
               sourceType: custom
               targetAttributeSource: com.tremolosecurity.mapping.DefaultEmail
             - targetAttributeName: first_name
               sourceType: user
               targetAttributeSource: givenName
             - targetAttributeName: last_name
               sourceType: user
               targetAttributeSource: sn
             - targetAttributeName: uid
               sourceType: user
               targetAttributeSource: uid
             onSuccess:
               - taskType: provision
                 sync: true
                 target: jitdb
                 setPassword: false
                 onlyPassedInAttributes: true
                 attributes:
                 - sub
                 - email
                 - first_name
                 - last_name
                 - uid
               {{ if .Capabilities.APIVersions.Has "project.openshift.io/v1/Project" }}
               - taskType: provision
                 sync: true
                 target: k8s
                 setPassword: false
                 onlyPassedInAttributes: true
                 attributes:
                 - sub
               {{ end }}
               - taskType: resync
                 keepExternalAttrs: false
                 changeRoot: true
                 newRoot: o=Tremolo
{{ end }}
{{ end }}