{{ if .Values.enable_impersonation }}
---
apiVersion: openunison.tremolo.io/v1
kind: Application
metadata:
  name: apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: openunison-applications
    app.kubernetes.io/part-of: openunison
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  azTimeoutMillis: 3000
  isApp: true
  urls:
  - hosts:
    - "#[K8S_API_HOST]"
    filterChain: 
    - className: com.tremolosecurity.proxy.filters.K8sInjectImpersonation
      params:
        targetName: k8s
        userNameAttribute: sub
        useLdapGroups: "false"
        groupAttribute: groups
    uri: "/"
    proxyTo: "${k8s_url}${fullURI}"
    authChain: oauth2jwt
    azRules:
    {{ if .Values.openunison.enable_provisioning }}
    {{ if .Values.openunison.naas.groups.external.enabled }}
    - constraint: (groups=k8s-cluster-k8s-administrators{{ .Values.openunison.naas.groups.external.suffix }})
      scope: filter
    {{ end }}
    {{ if .Values.openunison.naas.groups.internal.enabled }}
    - constraint: (groups=k8s-cluster-k8s-administrators{{ .Values.openunison.naas.groups.internal.suffix }})
      scope: filter
    {{ end }}
    {{ range $role := .Values.openunison.naas.groups.default }}
    - constraint: (groups=k8s-namespace-{{ $role.name }}-k8s-*)
      scope: filter
    {{ end }}
    {{ range $role := .Values.openunison.naas.groups.roles }}
    - constraint: (groups=k8s-namespace-{{ $role.name }}-k8s-*)
      scope: filter
    {{ end }}
    {{ else }}
    {{ $length := len .Values.openunison.az_groups }}
    {{ if eq $length 0 }}
    - scope: dn
      constraint: o=Tremolo
    {{ else }}
    {{ range $az_group := .Values.openunison.az_groups }}
    - scope: filter
      constraint: (groups={{ $az_group }})
    {{ end }}
    {{ end }}
    {{ end }}
    {{ $length := len .Values.openunison.extra_az_groups }}
    {{ if eq $length 0 }}
    {{ else }}
    {{ range $az_group := .Values.openunison.extra_az_groups }}
    - scope: filter
      constraint: (groups={{ $az_group }})
    {{ end }}
    {{ end }}
  cookieConfig:
    sessionCookieName: k8s-api-name
    domain: "#[K8S_API_HOST]"
    secure: true
    httpOnly: true
    logoutURI: "/logout"
    keyAlias: session-unison
    timeout: {{ .Values.network.session_inactivity_timeout_seconds }}
    scope: -1
    cookiesEnabled: false
{{ end }}