{{ if .Values.openunison.enable_provisioning }}

---
apiVersion: openunison.tremolo.io/v1
kind: Application
metadata:
  name: scale-ops
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: openunison-applications
    app.kubernetes.io/part-of: openunison
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  azTimeoutMillis: 3000
  isApp: true
  urls:
  {{ if .Values.openunison.html.legacy }}
  - hosts:
    - "#[OU_HOST]"
    filterChain: 
    - className: com.tremolosecurity.proxy.filters.XForward
      params:
        createHeaders: "false"
    - className: com.tremolosecurity.proxy.filters.SetNoCacheHeaders
      params: {}
    uri: "/ops"
    proxyTo: http://ouhtml-{{ .Release.Name }}.{{ .Release.Namespace }}.svc:8080${fullURI}
    authChain: login-service
    overrideHost: true
    overrideReferer: true
    azRules:
    - scope: filter
      constraint: "(groups=administrators{{ .Values.openunison.naas.groups.external.suffix }})"
    - scope: filter
      constraint: "(groups=administrators{{ .Values.openunison.naas.groups.internal.suffix }})"
    - scope: filter
      constraint: "(groups=security{{ .Values.openunison.naas.groups.external.suffix }})"
    - scope: filter
      constraint: "(groups=security{{ .Values.openunison.naas.groups.internal.suffix }})"
    results: 
      azFail: default-login-failure
      auFail: default-login-failure
  {{ end }}
  - hosts:
    - "#[OU_HOST]"
    filterChain:
    - className: com.tremolosecurity.scalejs.ws.ScaleJSOperator
      params:
        searchableAttributes:
          - givenName=First Name
          - sn=Last Name
          - mail=Email Address
          - uid=Login ID
        resultAttributes:
          - givenName=First Name
          - sn=Last Name
          - mail=Email Address
          - uid=Login ID
        scaleMainAppName: scale
        scaleMainURI: /scale/main
        homeUrl: /scale/
        bases:
        - OpenUnison=o=Tremolo
        {{ range $key,$value := .Values.openunison.naas.ops.searchBases }}
        - {{ $key }}={{ $value }}
        {{ end }}
        approveChecked: "{{ .Values.openunison.naas.ops.approveChecked }}"
        showPreApprove: "{{ .Values.openunison.naas.ops.showPreApprove }}"
        approvedLabel: "{{ .Values.openunison.naas.ops.approvedLabel }}"
        deniedLabel: "{{ .Values.openunison.naas.ops.deniedLabel }}"
        reasonApprovedLabel: "{{ .Values.openunison.naas.ops.reasonApprovedLabel }}"
        reasonDeniedLabel: "{{ .Values.openunison.naas.ops.reasonDeniedLabel }}"
        maxWidth: "{{ .Values.openunison.naas.ops.userDetailsMaxWidth | default "sm" }}"
        attributesWidth: "{{ .Values.openunison.naas.ops.userDetailsAttributeWidth | default "6" }}"
        rolesWith: "{{ .Values.openunison.naas.ops.userDetailsRolesWidth | default "6" }}"
    {{ if .Values.openunison.html.legacy }}
    uri: /ops/ops
    {{ else }}
    uri: /scale/ops
    {{ end }}
    
    {{ if .Values.openunison.naas.ops.azRules }}
    azRules:
    {{ range .Values.openunison.naas.ops.azRules }}
    - scope: {{ .scope }}
      constraint: {{ .constraint }}
    {{ end }}
    {{ else }}
    azRules:
    - scope: filter
      constraint: (groups=administrators{{ .Values.openunison.naas.groups.external.suffix }})
    - scope: filter
      constraint: "(groups=administrators{{ .Values.openunison.naas.groups.internal.suffix }})"
    {{ end }}
    authChain: login-service
    {{ if .Values.openunison.html.legacy }}
    results:
      azFail: default-login-failure
      auFail: default-login-failure
    {{ else }}
    results: {}
    {{ end }}
  cookieConfig:
    sessionCookieName: tremolosession
    domain: "#[OU_HOST]"
    secure: true
    httpOnly: true
    logoutURI: "/logout"
    keyAlias: session-unison
    timeout: {{ .Values.network.session_inactivity_timeout_seconds }}
    scope: -1
    cookiesEnabled: true
{{ end }}