{{- $root := . -}}
---
apiVersion: openunison.tremolo.io/v1
kind: Workflow
metadata:
  name: create-new-namespace
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  description: functional workflow for creating namespaces
  inList: false
  label: Create New Namespace
  orgId: 04901973-5f4c-46d9-9e22-55e88e168776
  tasks: |-
           {{ if .Values.openunison.naas.workflows.new_namespace.pre_run_workflow }}
           - taskType: callWorkflow
             name: {{ .Values.openunison.naas.workflows.new_namespace.pre_run_workflow }}
           {{ end }}

           - taskType: customTask
             className: com.tremolosecurity.provisioning.tasks.CheckForGit
             params: {}


           
             
             
           {{ if .Values.openunison.naas.groups.internal.enabled }}
           - taskType: customTask
             className: com.tremolosecurity.provisioning.customTasks.AddGroupToStore
             params:
               target: jitdb
               name: approvers-k8s-$cluster$-$nameSpace$
               attributes:
               - unison.group.create.sql=INSERT INTO localGroups (name,description) VALUES (?,?)
               - unison.group.create.param.2=Approve access to $cluster$ $nameSpace$
           {{ if $root.Capabilities.APIVersions.Has "project.openshift.io/v1/Project" }}
           - taskType: customTask
             className: com.tremolosecurity.provisioning.customTasks.AddGroupToStore
             params:
               target: k8s
               name: approvers-k8s-$cluster$-$nameSpace$
               attributes: []
           {{  end }}
             
           {{ range $role := .Values.openunison.naas.groups.default }}
           - taskType: customTask
             className: com.tremolosecurity.provisioning.customTasks.AddGroupToStore
             params:
               target: jitdb
               name: k8s-namespace-{{ $role.name }}-$cluster$-$nameSpace${{ $root.Values.openunison.naas.groups.internal.suffix }}
               attributes:
               - unison.group.create.sql=INSERT INTO localGroups (name,description) VALUES (?,?)
               - unison.group.create.param.2={{ $role.description }}
           {{ if $root.Capabilities.APIVersions.Has "project.openshift.io/v1/Project" }}
           - taskType: customTask
             className: com.tremolosecurity.provisioning.customTasks.AddGroupToStore
             params:
               target: k8s
               name: k8s-namespace-{{ $role.name }}-$cluster$-$nameSpace${{ $root.Values.openunison.naas.groups.internal.suffix }}
               attributes: []
           {{ end }}
           {{ end }}

           
           {{ range $role := .Values.openunison.naas.groups.roles }}
           - taskType: customTask
             className: com.tremolosecurity.provisioning.customTasks.AddGroupToStore
             params:
               target: jitdb
               name: k8s-namespace-{{ $role.name }}-$cluster$-$nameSpace${{ $root.Values.openunison.naas.groups.internal.suffix }}
               attributes:
               - unison.group.create.sql=INSERT INTO localGroups (name,description) VALUES (?,?)
               - unison.group.create.param.2={{ $role.description }}
           {{ if $root.Capabilities.APIVersions.Has "project.openshift.io/v1/Project" }}
           - taskType: customTask
             className: com.tremolosecurity.provisioning.customTasks.AddGroupToStore
             params:
               target: k8s
               name: k8s-namespace-{{ $role.name }}-$cluster$-$nameSpace${{ $root.Values.openunison.naas.groups.internal.suffix }}
               attributes: []
           {{ end }}
           {{ end }}
            
            
            
           {{ end }}

           {{ if .Values.openunison.naas.groups.external.enabled }}
           
           {{ if $root.Capabilities.APIVersions.Has "openunison.tremolo.io/v1/NamespaceGroupMetaData" }}
           - taskType: callWorkflow
             name: new-ns-nsgmd
           {{ else }}
           - taskType: callWorkflow
             name: new-ns-legacy-gmd
           {{ end }}

            
           {{ end }}

           {{ if .Values.openunison.naas.groups.internal.enabled }}
           {{ if .Values.openunison.naas.groups.internal.add_requestor_as_admin}}
           - taskType: mapping
             strict: true
             map:
               - targetAttributeName: uid
                 targetAttributeSource: uid
                 sourceType: user
             onSuccess:
               
               - taskType: addGroup
                 name: approvers-k8s-$cluster$-$nameSpace$
                 remove: false
               - taskType: addGroup
                 name: k8s-namespace-administrators-$cluster$-$nameSpace${{ .Values.openunison.naas.groups.internal.suffix }}
                 remove: false
               - taskType: provision
                 sync: false
                 target: jitdb
                 setPassword: false
                 onlyPassedInAttributes: false
                 attributes: ["uid"]
               {{ if $root.Capabilities.APIVersions.Has "project.openshift.io/v1/Project" }}
               - taskType: provision
                 sync: false
                 target: k8s
                 setPassword: false
                 onlyPassedInAttributes: false
                 attributes: ["uid"]
               {{ end }}
           {{ end }}
           {{ end }}

           {{ if .Values.openunison.naas.workflows.new_namespace.pre_provision_workflow }}
           - taskType: callWorkflow
             name: {{ .Values.openunison.naas.workflows.new_namespace.pre_provision_workflow }}
           {{ end }}

           {{ if .Values.openunison.naas.git.enable_byo }}
           # GitOps - Create SSH Key for Namespace
           - taskType: ifAttrHasValue
             name: useGit
             value: "true"
             onSuccess:
               - taskType: customTask
                 className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
                 params:
                   targetName: k8s
                   template: |-
                     kind: Secret
                     apiVersion: v1
                     metadata:
                       name: sshkey-namespace-$cluster$-$nameSpace$
                       namespace: openunison
                       labels:
                         cluster: $cluster$
                     data:
                       id_rsa: $b64sshkey$
                     type: Opaque
                   srcType: yaml
                   writeToRequest: "false"
           {{ end }}

           - taskType: customTask
             className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
             params:
               targetName: $cluster$
               template: |-
                  kind: Namespace
                  apiVersion: v1
                  metadata:
                    name: "$nameSpace$"
                    labels:
                      name: "$nameSpace$"
                      tremolo.io/request-access: $enableInternal$
                      {{ range $key,$value := .Values.openunison.naas.workflows.new_namespace.namespace_request_labels }}
                      {{ $key }}: "${{ $value }}$"
                      {{ end }}
                    annotations:
                      tremolo.io/managedByGit: "$useGit$"
                      $gitUrlAnnotation$
               kind: Namespace
               srcType: yaml
               writeToRequest: "$useGit$"
               requestAttribute: git-secret-cluster-k8s-$nameSpace$
               path: {{ $root.Values.openunison.naas.git.prefix }}/namespaces/$nameSpace$.yaml

           {{ if .Values.openunison.naas.workflows.new_namespace.post_namespace_create_workflow }}
           - taskType: callWorkflow
             name: {{ .Values.openunison.naas.workflows.new_namespace.post_namespace_create_workflow }}
           {{ end }}

           {{ if .Values.openunison.naas.groups.internal.enabled }}

           {{ range $role := .Values.openunison.naas.groups.default }}
           {{ range $bind := $role.bindings }}
           - taskType: customTask
             className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
             params:
               targetName: $cluster$
               template: |-
                    kind: RoleBinding
                    apiVersion: rbac.authorization.k8s.io/v1
                    metadata:
                      name: {{ $bind.binding }}-binding{{ $root.Values.openunison.naas.groups.internal.suffix }}
                      namespace: "$nameSpace$"
                    subjects:
                    - kind: Group
                      name: k8s-namespace-{{ $role.name }}-$cluster$-$nameSpace${{ $root.Values.openunison.naas.groups.internal.suffix }}
                      apiGroup: rbac.authorization.k8s.io
                    roleRef:
                      kind: {{ $bind.type }}
                      name: {{ $bind.name }}
                      apiGroup: rbac.authorization.k8s.io
               kind: RoleBinding
               srcType: yaml
               writeToRequest: "$useGit$"
               requestAttribute: git-secret-namespace-$cluster$-$nameSpace$
               path: $gitPath$/$nameSpace$/rolebindings/{{ $bind.binding }}-binding{{ $root.Values.openunison.naas.groups.internal.suffix }}.yaml
           {{ end }}
           {{ end }}
           {{ range $role := .Values.openunison.naas.groups.roles }}
           {{ range $bind := $role.bindings }}
           - taskType: customTask
             className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
             params:
               targetName: $cluster$
               template: |-
                    kind: RoleBinding
                    apiVersion: rbac.authorization.k8s.io/v1
                    metadata:
                      name: {{ $bind.binding }}-binding{{ $root.Values.openunison.naas.groups.internal.suffix }}
                      namespace: "$nameSpace$"
                    subjects:
                    - kind: Group
                      name: k8s-namespace-{{ $role.name }}-$cluster$-$nameSpace${{ $root.Values.openunison.naas.groups.internal.suffix }}
                      apiGroup: rbac.authorization.k8s.io
                    roleRef:
                      kind: {{ $bind.type }}
                      name: {{ $bind.name }}
                      apiGroup: rbac.authorization.k8s.io
               srcType: yaml
               writeToRequest: "$useGit$"
               requestAttribute: git-secret-namespace-$cluster$-$nameSpace$
               path: $gitPath$/$nameSpace$/rolebindings/{{ $bind.binding }}-binding{{ $root.Values.openunison.naas.groups.internal.suffix }}.yaml
           {{ end }}
           {{ end }}
           {{ end }}

           {{ if .Values.openunison.naas.groups.external.enabled }}

           {{ range $role := .Values.openunison.naas.groups.default }}
           {{ range $bind := $role.bindings }}
           - taskType: ifAttrHasValue
             name: {{ $role.external.fieldName }}
             value: ""
             onFailure:
              - taskType: customTask
                className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
                params:
                  targetName: $cluster$
                  template: |-
                        kind: RoleBinding
                        apiVersion: rbac.authorization.k8s.io/v1
                        metadata:
                          name: {{ $bind.binding }}-binding{{ $root.Values.openunison.naas.groups.external.suffix }}
                          namespace: "$nameSpace$"
                        subjects:
                        - kind: Group
                          name: k8s-namespace-{{ $role.name }}-$cluster$-$nameSpace${{ $root.Values.openunison.naas.groups.external.suffix }}
                          apiGroup: rbac.authorization.k8s.io
                        roleRef:
                          kind: {{ $bind.type }}
                          name: {{ $bind.name }}
                          apiGroup: rbac.authorization.k8s.io
                  srcType: yaml
                  writeToRequest: "$useGit$"
                  requestAttribute: git-secret-namespace-$cluster$-$nameSpace$
                  path: $gitPath$/$nameSpace$/rolebindings/{{ $bind.binding }}-binding{{ $root.Values.openunison.naas.groups.external.suffix }}.yaml
           {{ end }}
           {{ end }}
           {{ range $role := .Values.openunison.naas.groups.roles }}
           {{ range $bind := $role.bindings }}
           - taskType: ifAttrHasValue
             name: {{ $role.external.fieldName }}
             value: ""
             onFailure:
              - taskType: customTask
                className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
                params:
                  targetName: $cluster$
                  template: |-
                        kind: RoleBinding
                        apiVersion: rbac.authorization.k8s.io/v1
                        metadata:
                          name: {{ $bind.binding }}-binding{{ $root.Values.openunison.naas.groups.external.suffix }}
                          namespace: "$nameSpace$"
                        subjects:
                        - kind: Group
                          name: k8s-namespace-{{ $role.name }}-$cluster$-$nameSpace${{ $root.Values.openunison.naas.groups.external.suffix }}
                          apiGroup: rbac.authorization.k8s.io
                        roleRef:
                          kind: {{ $bind.type }}
                          name: {{ $bind.name }}
                          apiGroup: rbac.authorization.k8s.io
                  srcType: yaml
                  writeToRequest: "$useGit$"
                  requestAttribute: git-secret-namespace-$cluster$-$nameSpace$
                  path: $gitPath$/$nameSpace$/rolebindings/{{ $bind.binding }}-binding{{ $root.Values.openunison.naas.groups.external.suffix }}.yaml
           {{ end }}
           {{ end }}
           {{ end }}


           - taskType: ifAttrHasValue
             name: useGit
             value: "true"
             onSuccess:
               # GitOps - Run Job to push to cluster repo
               - taskType: customTask
                 className: com.tremolosecurity.provisioning.tasks.PushToGit
                 params:
                   secretName: sshkey-cluster-$cluster$
                   nameSpace: openunison
                   target: k8s
                   keyName: id_rsa
                   gitRepo: $clusterGitUrl$
                   requestObject: git-secret-cluster-k8s-$nameSpace$
                   commitMsg: For workflow $WORKFLOW.id$

               # GitOps - Run Job to push to namespace repo
               - taskType: customTask
                 className: com.tremolosecurity.provisioning.tasks.PushToGit
                 params:
                   secretName: sshkey-namespace-$cluster$-$nameSpace$
                   nameSpace: openunison
                   target: k8s
                   keyName: id_rsa
                   gitRepo: $namespaceGitUrl$
                   requestObject: git-secret-namespace-$cluster$-$nameSpace$
                   commitMsg: For workflow $WORKFLOW.id$

               

           - taskType: customTask
             className: com.tremolosecurity.provisioning.customTasks.LoadAttributes
             params:
               nameAttr: uid
               name: 
               - givenName
               - sn
               - mail

           #  - taskType: customTask
           #    className: com.tremolosecurity.provisioning.customTasks.PrintUserInfo
           #    params:
           #      message: pre-email-notification

           - taskType: notifyUser
             subject: {{ .Values.openunison.naas.workflows.new_namespace.notification.subject }}
             mailAttrib: mail
             msg: |-
{{ .Values.openunison.naas.workflows.new_namespace.notification.msg | indent 17 }}