---
apiVersion: openunison.tremolo.io/v1
kind: Workflow
metadata:
  name: k8s-delete-workflow
  namespace: {{ .Release.Namespace }}
spec:
  description: Delete Namespace
  inList: false
  label: Delete Namespace
  orgId: 04901973-5f4c-46d9-9e22-55e88e168776
  tasks: |-
           - taskType: customTask
             className: com.tremolosecurity.provisioning.customTasks.LoadAttributes
             params:
               nameAttr: uid
               name: 
               - givenname
               - sn
               - mail

           - taskType: customTask
             className: com.tremolosecurity.provisioning.tasks.CheckForGit
             params:
               namespace: $nameSpace$


           - taskType: approval
             emailTemplate: A namespace owner has requested deletion
             mailAttr: mail
             failureEmailSubject: Namespace deletion not approved
             failureEmailMsg: |-
               Because:
               ${reason}
             label: Request Delete Namespace - $cluster$ - $nameSpace$
             approvers:
             - scope: group
               constraint: cn=administrators{{ .Values.openunison.naas.groups.external.suffix }},ou=groups,ou=shadow,o=Tremolo
             - scope: group
               constraint: cn=administrators{{ .Values.openunison.naas.groups.internal.suffix }},ou=groups,ou=shadow,o=Tremolo
             onSuccess:
             - taskType: customTask
               className: com.tremolosecurity.provisioning.customTasks.PrintUserInfo
               params:
                 message: post-approval
             - taskType: callWorkflow
               name: k8s-delete-namespace