---
apiVersion: openunison.tremolo.io/v1
kind: Target
metadata:
  name: azuread
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.provisioning.core.providers.AzureADProvider
  params:
  {{ if not .Values.oidc.client_id_is_secret  }}
  - name: clientId
    value: "{{ .Values.oidc.client_id }}"
  {{ end }}
  - name: tenantId
    value: "{{ .Values.azure.tennant_id }}"
  secretParams:
  - name: clientSecret
    secretName: orchestra-secrets-source#[openunison.static-secret.suffix]
    secretKey: OIDC_CLIENT_SECRET
  {{ if .Values.oidc.client_id_is_secret }}
  - name: clientId
    secretName: orchestra-secrets-source#[openunison.static-secret.suffix]
    secretKey: OIDC_CLIENT_ID
  {{ end }}
  targetAttributes:
  - name: displayName
    source: displayName
    sourceType: user
  - name: givenName
    source: givenName
    sourceType: user
  - name: surname
    source: surname
    sourceType: user
  - name: userPrincipalName
    source: userPrincipalName
    sourceType: user
  - name: id
    source: id
    sourceType: user
  - name: mail
    source: mail
    sourceType: user
  - name: accountEnabled
    source: accountEnabled
    sourceType: user